exec: ../positionsites
args:
    - -e
    - production
host: "*.*"
extra-hosts:
    - "*.*.*"
postgres: false
redirects:
    - from: abingdonsquarepainters.com
      to: www.abingdonsquarepainters.com